### ISSUE TITLE
Instructions missing

### ISSUE THREAD

**Issue by EitanTal** [betwo/vscode-doxygen-runner#3]
The readme.md does not provide instructions on how to use and configure this extension.

Please provide details:
1. (Usage) Mention that this extension registers 2 commands: generate doxygen and view doxygen. (accessible from F1)
2. (Config) How do I define the path for doxyfile?
3. (Config) How do I define the path for the result index.html?

Also, the view command does nothing when I try to launch it. I suppose this is because the path to the resulting index.html is not defined.

**Comment by betwo** [comment]
Hi @EitanTal, thank you for your feedback. You're right, the `README.md` definitely needed an overhaul.

> (Config) How do I define the path for doxyfile?

Until now it was actually not possible to explicitly specify the configuration file to use.
The "correct" file is searched for relative to the currently opened file (as the `README.md` hinted at.)
However, with version `1.6.0` it is now also possible to override this behavior and specify `doxygen_runner.configuration_file_override`.

> (Config) How do I define the path for the result index.html?

This has to be specified in the `Doxyfile` under `OUTPUT_DIRECTORY`.
I considered an override option here as well, but that would require copying the configuration file, modifying `OUTPUT_DIRECTORY` and then generating the result, which I think is way to error-

> Also, the view command does nothing when I try to launch it. I suppose this is because the path to the resulting index.html is not defined.

Yes, the view command only works once the documentation is successfully generated.

Could you please try again with the latest update?

**Comment by EitanTal** [comment]
I can generate & override, but the view command still doesn't work. (Nothing happens)

I followed the instructions and successfully defined the path to doxyfile. The readme didn't mention that the insertion is done in settings.json.

**Comment by betwo** [comment]
> I can generate & override, but the view command still doesn't work. (Nothing happens)

Nice, that generating works for you now! It is strange, though, there should be an error message when viewing the result fails. 

Could you please open the developer tools and filter the console log for  `vscode-doxygen-runner`?

![image](https://user-images.githubusercontent.com/4789818/87222039-c9f12900-c370-11ea-9526-66bdfa46cc48.png)

![image](https://user-images.githubusercontent.com/4789818/87222007-96ae9a00-c370-11ea-9073-246fd82efac0.png)

Are there any error messages? Maybe you could also attach the log file here?


> I followed the instructions and successfully defined the path to doxyfile. The readme didn't mention that the insertion is done in settings.json.

Well, you could also set the option the settings GUI, did that not show up for you?
![image](https://user-images.githubusercontent.com/4789818/87221964-40d9f200-c370-11ea-80e4-806809feb9a2.png)

**Comment by EitanTal** [comment]
![image](https://user-images.githubusercontent.com/7789714/87966286-ae79d280-ca82-11ea-8040-b7c4f3a4713e.png)

**Comment by EitanTal** [comment]
I was unaware that I can edit the extension settings from the GUI.

![image](https://user-images.githubusercontent.com/7789714/87966487-f13baa80-ca82-11ea-9068-2350a59d02d1.png)

**Comment by betwo** [comment]
Ah, I think I see the problem: Do you have 
```
OUTPUT_DIRECTORY = C:\RemMon\sw\FirmwareRepo\doc\doxygen\
```
in your Doxyfile?

In that case, could you please try the latest version (>=1.7.1)? This should also support absolute paths in that place.

**Comment by EitanTal** [comment]
Ok, now viewing it works! Nice job!

however, I now get an error when I try to generate, and I didn't get this error before: (Introduced in 1.7.1. Switching back to 1.7.0 made this problem go away)
![image](https://user-images.githubusercontent.com/7789714/88222556-c5a7f400-cc2b-11ea-8beb-141692d2a36e.png)
![image](https://user-images.githubusercontent.com/7789714/88222597-d3f61000-cc2b-11ea-8135-3ce895424cde.png)

I have doxygen installed here:
```
 Directory of C:\Program Files\doxygen\bin

02-Jul-20  08:57 AM    <DIR>          .
02-Jul-20  08:57 AM    <DIR>          ..
13-Apr-20  11:08 AM        18,201,088 doxygen.exe
13-Apr-20  11:08 AM         1,530,368 doxyindexer.exe
13-Apr-20  11:08 AM         1,185,792 doxysearch.cgi.exe
13-Apr-20  10:51 AM         8,477,184 doxywizard.exe
01-Aug-17  08:16 AM        44,775,936 libclang.dll
               5 File(s)     74,170,368 bytes
               2 Dir(s)  44,359,966,720 bytes free

```

**Comment by betwo** [comment]
Nice, thank you for testing again!
After some debugging I assume that the error was due to `doxygen` being run in your `OUTPUT_DIRECTORY` which might not have existed.

With version 1.7.2 this should hopefully not be the case anymore, could you please try again?
I also added some debug logging in case it still doesn't work.

**Comment by EitanTal** [comment]
Confirmed! Generating & viewing works! Closing issue.
